In [2]:
import numpy as np

# Exercise 1: 
Determine if w is a linear combination of the vectors below

In [ ]:
def check_linear_combination(matrix, w):
  matrix_w = np.column_stack((matrix, w))
  # print(matrix_w)
  a1 = np.linalg.matrix_rank(matrix)
  a2 = np.linalg.matrix_rank(matrix_w)
  
  if a1 == a2:
    print("w is linear combination of the vectors")
  else:
    print("w is NOT linear combination of the vectors")

wa = np.array([3, -6, 17, 11])
A = np.array([
    [1, -1, 0],
    [2, 0, 5],
    [3, 1, -6],
    [4, 3, 8]
])


wb = np.array([0, 5, 3, 0]) 
B = np.array([
    [1, 2, 2],
    [1, 3, -1],
    [2, 5, 3],
    [2, 6, 6]
])


C = np.array([
    [1, 2, 2],
    [1, 3, -1],
    [2, 5, 3],
    [2, 6, 6]
])
wc = np.array([-1, 6, 1, -4])


check_linear_combination(A, wa)
check_linear_combination(B, wb)
check_linear_combination(C, wc)

[[ 1 -1  0  3]
 [ 2  0  5 -6]
 [ 3  1 -6 17]
 [ 4  3  8 11]]
w is NOT linear combination of the vectors
[[ 1  2  2  0]
 [ 1  3 -1  5]
 [ 2  5  3  3]
 [ 2  6  6  0]]
w is NOT linear combination of the vectors
[[ 1  2  2 -1]
 [ 1  3 -1  6]
 [ 2  5  3  1]
 [ 2  6  6 -4]]
w is linear combination of the vectors


# Another way:

In [ ]:
def verify_linear_combination(v1, v2, v3, w):


  C = np.transpose([v1, v2, v3, w])
  # print(C) 
  rankC = np.linalg.matrix_rank(C)
  a1 = np.linalg.matrix_rank(rankC)
  a2 = np.linalg.matrix_rank(C)
  if a1 == a2:
    print("C is linear independent")
  else:
    print("C is NOT linear independent")


v1c = np.array([1, 1, 2, 2])
v2c = np.array([2, 3, 5, 6])
v3c = np.array([2, -1, 3, 6])
wc = np.array([-1, 6 , 1, -4])
verify_linear_combination(v1c, v2c, v3c, wc)


def verify_linear_combination_4v(v1, v2, v3, v4, w):
  C = np.transpose([v1, v2, v3, v4, w])
  
  rankC = np.linalg.matrix_rank(C)

  if rankC == C.shape[1]:
    print("w is linear combination of the vectors")
  else:
    print("w is NOT linear combination of the vectors")

v1d = np.array([1, 2, 3, 4])
v2d = np.array([-1, 0, 1, 3])
v3d = np.array([0, 5, -6, 8])
v4d = np.array([1, 15, -12, 8])
wd = np.array([0, -6, 17, 11])
verify_linear_combination_4v(v1d, v2d, v3d, v4d, wd)

C is NOT linear independent
w is NOT linear combination of the vectors


# Exercise 2: 
Write program to verify

In [ ]:
def verify_linearly_independent(matrix):
    rank_A = np.linalg.matrix_rank(matrix)

    if rank_A == A.shape[1]:
        print("C is linear independent")
    else:
        print("C is NOT linear independent")


A_matrix = np.array([
    [1, -2, 0],
    [0, -4, 1],
    [1, -1, 1]
])

# B
B = np.array([[1, 0, 2],
              [0, 1, 4],
              [2, -2, -4]])

rank_A = np.linalg.matrix_rank(A)

if rank_A == A.shape[1]:
    print("The given vectors are linearly independent.")
else:
    print("The given vectors are linearly dependent.")

a = 1
b = -2
c = (a, b, c) = (-1/2, 1/2, 1) * np.array([a, b, 0])

print(f"a = {a}, b = {b}, c = {c}")

# C
A = np.array([[1, -2, 3, 4],
              [2, 4, 5, 0],
              [-2, 0, 0, 4],
              [3, 2, 1, -1]])

rank_A = np.linalg.matrix_rank(A)

if rank_A == A.shape[0]:
    print("The given vectors are linearly independent.")
else:
    print("The given vectors are linearly dependent.")

# D
A = np.array([[0, 0, 1, 2, 3],
              [0, 0, 2, 3, 1],
              [1, 2, 3, 4, 5],
              [2, 1, 0, 0, 0],
              [-1, -3, -5, 0, 0]])

rank_A = np.linalg.matrix_rank(A)

if rank_A == A.shape[0]:
    print("The given vectors are linearly independent.")
else:
    print("The given vectors are linearly dependent.")


C is linear independent


# Exercise 3: 
Let the matrix

In [3]:
C = np.array([
    [1, 0, 2, 3],
    [4, -1, 0, 2],
    [0, -1, -8, -10]
])



[[  1   0   2   3]
 [  4  -1   0   2]
 [  0  -1  -8 -10]]


In [4]:
print(C)

[[  1   0   2   3]
 [  4  -1   0   2]
 [  0  -1  -8 -10]]
